

spring:
    application:
        name: B-Service
    main:
        show-banner: true

    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

server:
    port: 8002
    contextPath: /ls
    undertow:
        io-threads: 32
        worker-threads: 256

