

spring:
    application:
        name: C-Service
    main:
        show-banner: true

    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

server:
    port: 8003
    contextPath: /cs
    undertow:
        io-threads: 32
        worker-threads: 256

